### ISSUE TITLE
com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnectionP2.isConnected

### ISSUE THREAD

**Issue by smworks** [Gurgen/SignalR-.net-core-android-client#25]
We have a following code in production:
`if (connection == null || !connection!!.isConnected) {
                    disconnectSignalR()
                    connectSignalR()
                }`

In crashlytics I'm seeing following exception:
`Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'boolean l.a.a.b.isOpen()' on a null object reference
com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnectionP2.isConnected (WebSocketHubConnectionP2.java:3)
`

It seems that isConnected method is faulty and even though connection object is initiliazed it's inner client is still null and instead of returning simple false, we get a nasty NPE.

Is there a different way to check if connection is opened?

**Comment by StevenFung96** [comment]
I'm having the same issue as well. Is there any other way to check is the connection being connected? 

`     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.java_websocket.client.WebSocketClient.isOpen()' on a null object reference
        at com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnectionP2.isConnected(WebSocketHubConnectionP2.java:202)
        at com.ixonus.letsgo.MainActivity.onCreate(MainActivity.kt:50)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6729) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by StevenFung96** [comment]
I'm having the same issue as well. Is there any other way to check is the connection being connected?

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.java_websocket.client.WebSocketClient.isOpen()' on a null object reference at com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnectionP2.isConnected(WebSocketHubConnectionP2.java:202)`

**Comment by zainkhalid91** [comment]
were you able to solve this problem?
